root: true
parser: "vue-eslint-parser"
plugins: 
  - "@typescript-eslint"
  - "vue"
extends: 
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:vue/strongly-recommended"
  - "standard"
  - "@nuxtjs/eslint-config-typescript"
  - "prettier"
parserOptions:
  sourceType: "module"
  parser: "@typescript-eslint/parser"
env:
  browser: true
  es2021: true
rules:
  vue/require-v-for-key: off
  "@typescript-eslint/ban-ts-comment": off
  "@typescript-eslint/explicit-module-boundary-types": off
