root: true
parser: "@typescript-eslint/parser"
plugins: 
  - "@typescript-eslint"
extends: 
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended
  - "standard"
  - "prettier"
parserOptions:
  sourceType: "module"
env:
  browser: true
  es2021: true
